---
title: "Homework4"
author: "Micha³ Frej"
date: "Thursday, October 29, 2015"
output: html_document
---
Zacznê od wprowadzenia wspólnych oznaczeñ.
```{r,message=FALSE,warning=FALSE}
alpha <- 0.7
k <- 3
m <- 4
g <- 900
N <- k*m*g
ILE <- 2000
istotnosc <- 0.05
```

##Czêœæ1
Tworzê zbiór, w którym efekt addytywny wynosi ok. 0.7 dla pewnej grupy.
```{r,message=FALSE,warning=FALSE}
set.seed(8)
data_set <- data.frame(GroupA = as.factor(sort(rep(1:k,N/k))),
                       GroupB = as.factor(rep(1:m,N/m)))

data_set$X <- rnorm(N,mean = alpha*(data_set$GroupA==1) , sd=1)

model <- aov(X~GroupA*GroupB, data = data_set)
model.tables(model)

anova(lm(X~GroupA*GroupB, data = data_set))
by(data_set$X,data_set$GroupA,mean)
```
Symulujemy moc F-testu
```{r,message=F,warning=FALSE}
data_set <- data.frame(GroupA = as.factor(sort(rep(1:k,N/k))),
                       GroupB = as.factor(rep(1:m,N/m)))
FTest_1 <- numeric(ILE)
FTest_2 <- numeric(ILE)
FTest_3 <- numeric(ILE)
for(i in 1:ILE){
      data_set$X <- rnorm(N,mean = alpha*(data_set$GroupA==1) , sd=1)
      AN <- anova(lm(X~GroupA*GroupB, data = data_set))
      FTest_1[i] <- AN[1,5]
      FTest_2[i] <- AN[2,5]
      FTest_3[i] <- AN[3,5]
}
mean(FTest_1)
mean(FTest_2)
mean(FTest_3)
```

##Czêœæ2
Tym razem interakcja wynosi ok. 0.7 dla grupy A=1, B=1.
```{r,message=FALSE,warning=FALSE}
set.seed(8)
data_set_2 <- data.frame(GroupA = as.factor(sort(rep(1:k,N/k))),
                       GroupB = as.factor(rep(1:m,N/m)))

data_set_2$X <- rnorm(N,mean = alpha*(data_set_2$GroupA==1 & data_set_2$GroupB==1) , sd=1)

A1B1 <- which(data_set_2$GroupA==1 & data_set_2$GroupB==1)
mean(data_set_2[A1B1,]$X)-mean(data_set_2[-(A1B1),]$X)
```
Symulujemy moc F-testu
```{r,message=F,warning=FALSE}
data_set_2 <- data.frame(GroupA = as.factor(sort(rep(1:k,N/k))),
                       GroupB = as.factor(rep(1:m,N/m)))
FTest_1 <- numeric(ILE)
FTest_2 <- numeric(ILE)
FTest_3 <- numeric(ILE)
for(i in 1:ILE){
      data_set_2$X <- rnorm(N,mean = alpha*(data_set_2$GroupA==1 & data_set_2$GroupB==1) , sd=1)
      AN <- anova(lm(X~GroupA*GroupB, data = data_set))
      FTest_1[i] <- AN[1,5]
      FTest_2[i] <- AN[2,5]
      FTest_3[i] <- AN[3,5]
}
mean(FTest_1>istotnosc)
mean(FTest_2>istotnosc)
mean(FTest_3>istotnosc)
```
##Czêœæ3
Zgodnie z tabelk¹ na stronie 89, tworzê przyk³ad, w którym alfa1 = 0.7 oraz  gamma11=0.7.
```{r,message=FALSE,warning=FALSE}
set.seed(8)
data_set_3 <- data.frame(GroupA = as.factor(sort(rep(1:k,N/k))),
                         GroupB = as.factor(rep(1:m,N/m)))

data_set_3$X <- rnorm(N,mean = alpha*(data_set_3$GroupA==1) +
                  alpha*(data_set_3$GroupA==1 & data_set_3$GroupB==1) -
                  (alpha/(m-1))*(data_set_3$GroupA==1 & data_set_3$GroupB!=1), sd=1)

A1B1 <- which(data_set_3$GroupA==1 & data_set_3$GroupB==1)
A1BN1 <- which(data_set_3$GroupA==1 & data_set_3$GroupB!=1)
A1 <- which(data_set_3$GroupA==1)

mean(data_set_3[A1B1,]$X)-mean(data_set_3[A1,]$X)
by(data_set_3$X,data_set_3$GroupA,mean)
```
Symulujemy moc F-testu
```{r,message=F,warning=FALSE}
data_set_3 <- data.frame(GroupA = as.factor(sort(rep(1:k,N/k))),
                         GroupB = as.factor(rep(1:m,N/m)))
FTest_1 <- numeric(ILE)
FTest_2 <- numeric(ILE)
FTest_3 <- numeric(ILE)
for(i in 1:ILE){
      data_set_3$X <- rnorm(N,mean = alpha*(data_set_3$GroupA==1) +
                  alpha*(data_set_3$GroupA==1 & data_set_3$GroupB==1) -
                  (alpha/(m-1))*(data_set_3$GroupA==1 & data_set_3$GroupB!=1), sd=1)

      AN <- anova(lm(X~GroupA*GroupB, data = data_set))
      FTest_1[i] <- AN[1,5]
      FTest_2[i] <- AN[2,5]
      FTest_3[i] <- AN[3,5]
}
mean(FTest_1)
mean(FTest_2)
mean(FTest_3)
```

